server:
  port: 7001
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#       defaultZone: http://localhost:7001/eureka/
spring:
  application:
    name: eureka-server