spider:
  bilibili:
    manga:
      manga-save-path: /users/zpl/dev/manga

eureka:
  client:
    service-url:
      defaultZone: http://172.18.0.4:7001/eureka/
  instance:
    ip-address: 192.168.139.100
    non-secure-port: 8888
