#该模块使用mybatis-plus连接数据库
spring:
  datasource:
    url: jdbc:mysql://ip:port/bilibili?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: password
    hikari:
      max-lifetime: 20000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true