#该模块使用mybatis-plus连接数据库
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.3.153:4567/bilibili?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false
#    username: root
#    password: zxcvbnm,./
#    hikari:
#      max-lifetime: 20000

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
spider:
  dao:
    create-table-path: E:\