
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
spider:
  dao:
    create-table-path: E:\

spring:
  application:
    name: common-dao-center

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
#  instance:
#    ip-address: true
server:
  port: 8087