spring:
  cloud:
    config:
      server:
        git:
          private-key:

        prefix:
          config
        bootstrap: true
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:2233/eureka/
