server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://10.8.0.1:32710/eureka
    register-with-eureka: false
  instance:
    ip-address: true
#logging:
#  config: classpath:logback-spring.xml