server:
  port: 8089
eureka:
  client:
    service-url:
      defaultZone: http://10.8.0.1:32710/eureka
    register-with-eureka: false
  instance:
    ip-address: true
#logging:
#  config: classpath:logback-spring.xml

spider:
  common:
    redis:
      redis-address: redis://10.8.0.1:31210
      redis-password: 123456
spring:
  rabbitmq:
    host: 10.8.0.1
    port: 30762
    username: admin
    password: admin