server:
  port: 8089
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: common-gateway
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.32.128
    non-secure-port: 8089
  client:
    service-url:
      defaultZone: http://172.18.0.4:7001/eureka/