server:
  port: 8080

spring:
  application:
    name: common-read-local
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

logging:
  level:
    cn.zpl: DEBUG

comic:
  folder:
    path: C:\Users\zpl\Desktop\Mac电脑
  cover:
    cache:
      path: ./cover-cache
